#!/usr/bin/env python3
"""
SRT to Furigana ASS Converter

This script converts SRT subtitle files to ASS format with furigana (ruby text)
for Japanese text. It processes all SRT files in the specified directory.

Usage:
    python srt_to_furigana_ass.py [input_directory] [output_directory]

If no directories are specified, it uses the current directory for both input and output.
"""

import os
import sys
import re
import pysrt
import argparse
from pathlib import Path

# Default style settings
DEFAULT_FONT = "Arial"
DEFAULT_FONT_SIZE = 48
DEFAULT_RUBY_FONT_SIZE = 24
DEFAULT_TEXT_COLOR = "&H00FFFFFF"  # White in ASS format (AABBGGRR)
DEFAULT_RUBY_COLOR = "&H00FFFFFF"  # White in ASS format
DEFAULT_OUTLINE_COLOR = "&H00000000"  # Black in ASS format
DEFAULT_SHADOW_COLOR = "&H00000000"  # Black in ASS format
DEFAULT_OUTLINE_SIZE = 2
DEFAULT_RUBY_OUTLINE_SIZE = 1
DEFAULT_SHADOW_SIZE = 2
DEFAULT_RUBY_SHADOW_SIZE = 1

def create_ass_from_srt(srt_file, output_dir=None, config=None):
    """
    Convert an SRT file to ASS format with furigana.
    
    Args:
        srt_file (str): Path to the SRT file
        output_dir (str, optional): Directory to save the output ASS file
        config (dict, optional): Configuration options for styling
    
    Returns:
        str: Path to the output ASS file
    """
    try:
        # Use default config if none provided
        if config is None:
            config = {
                'font': DEFAULT_FONT,
                'font_size': DEFAULT_FONT_SIZE,
                'ruby_font_size': DEFAULT_RUBY_FONT_SIZE,
                'text_color': DEFAULT_TEXT_COLOR,
                'ruby_color': DEFAULT_RUBY_COLOR,
                'outline_color': DEFAULT_OUTLINE_COLOR,
                'shadow_color': DEFAULT_SHADOW_COLOR,
                'outline_size': DEFAULT_OUTLINE_SIZE,
                'ruby_outline_size': DEFAULT_RUBY_OUTLINE_SIZE,
                'shadow_size': DEFAULT_SHADOW_SIZE,
                'ruby_shadow_size': DEFAULT_RUBY_SHADOW_SIZE
            }
        
        # Parse the SRT file
        subs = pysrt.open(srt_file)
        
        # Create output file path
        srt_path = Path(srt_file)
        if output_dir:
            output_path = Path(output_dir) / f"{srt_path.stem}.ass"
        else:
            output_path = srt_path.with_suffix('.ass')
        
        # Create a basic ASS file with proper ruby text support
        ass_content = f"""[Script Info]
; Script generated by srt_to_furigana_ass.py
ScriptType: v4.00+
PlayResX: 1920
PlayResY: 1080
WrapStyle: 0
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,{config['font']},{config['font_size']},{config['text_color']},&H000000FF,{config['outline_color']},{config['shadow_color']},0,0,0,0,100,100,0,0,1,{config['outline_size']},{config['shadow_size']},2,10,10,20,1
Style: Ruby,{config['font']},{config['ruby_font_size']},{config['ruby_color']},&H000000FF,{config['outline_color']},{config['shadow_color']},0,0,0,0,100,100,0,0,1,{config['ruby_outline_size']},{config['ruby_shadow_size']},8,10,10,20,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
        
        # Add each subtitle as a dialogue line
        for sub in subs:
            start_time = format_time(sub.start.hours, sub.start.minutes, 
                                    sub.start.seconds, sub.start.milliseconds)
            end_time = format_time(sub.end.hours, sub.end.minutes, 
                                  sub.end.seconds, sub.end.milliseconds)
            
            # Clean the text and add ruby tags
            text = add_ruby_tags(sub.text, config)
            
            # Add the dialogue line
            ass_content += f"Dialogue: 0,{start_time},{end_time},Default,,0,0,0,,{text}\n"
        
        # Write the ASS file
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(ass_content)
        
        print(f"Converted {srt_file} to {output_path}")
        return str(output_path)
    
    except Exception as e:
        print(f"Error converting {srt_file}: {e}")
        return None

def format_time(hours, minutes, seconds, milliseconds):
    """Format time for ASS format."""
    return f"{hours}:{minutes:02d}:{seconds:02d}.{milliseconds:02d}"

def add_ruby_tags(text, config=None):
    """
    Add ASS ruby tags to text with furigana in parentheses.
    
    This function uses a regular expression to find patterns like:
    - 漢字(かんじ)
    - 日本語(にほんご)
    
    And converts them to ASS ruby format using the proper tag:
    - {\\rt(かんじ)}漢字
    - {\\rt(にほんご)}日本語
    
    The \\rt tag is the correct way to implement ruby text in ASS.
    
    Args:
        text (str): The text to process
        config (dict, optional): Configuration options for styling
    
    Returns:
        str: Text with ASS ruby tags
    """
    # Replace newlines with ASS newline format
    text = text.replace('\n', '\\N')
    
    # Define the pattern for finding kanji with furigana in parentheses
    # This pattern looks for any non-whitespace characters followed by text in parentheses
    pattern = r'(\S+?)\(([^)]+)\)'
    
    # Function to replace matches with ASS ruby tags
    def replace_with_ruby(match):
        kanji = match.group(1)
        furigana = match.group(2)
        
        # Use the standard \rt tag for ruby text
        # This is the correct implementation according to the ASS specification
        return f"{{\\rt({furigana})}}{kanji}"
    
    # Apply the replacement
    result = re.sub(pattern, replace_with_ruby, text)
    
    return result

def process_directory(input_dir='.', output_dir=None, config=None):
    """
    Process all SRT files in the input directory.
    
    Args:
        input_dir (str): Directory containing SRT files
        output_dir (str, optional): Directory to save the output ASS files
        config (dict, optional): Configuration options for styling
    """
    input_path = Path(input_dir)
    
    # Create output directory if it doesn't exist
    if output_dir:
        output_path = Path(output_dir)
        output_path.mkdir(exist_ok=True)
    else:
        output_path = input_path
    
    # Find all SRT files
    srt_files = list(input_path.glob('*.srt'))
    
    if not srt_files:
        print(f"No SRT files found in {input_dir}")
        return
    
    print(f"Found {len(srt_files)} SRT files in {input_dir}")
    
    # Process each SRT file
    for srt_file in srt_files:
        create_ass_from_srt(str(srt_file), str(output_path), config)

def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(description='Convert SRT files to ASS with furigana support')
    parser.add_argument('input_dir', nargs='?', default='.', help='Input directory containing SRT files')
    parser.add_argument('output_dir', nargs='?', help='Output directory for ASS files')
    
    # Style options
    parser.add_argument('--font', default=DEFAULT_FONT, help='Font to use for subtitles')
    parser.add_argument('--font-size', type=int, default=DEFAULT_FONT_SIZE, help='Font size for main text')
    parser.add_argument('--ruby-font-size', type=int, default=DEFAULT_RUBY_FONT_SIZE, help='Font size for ruby text')
    parser.add_argument('--text-color', default=DEFAULT_TEXT_COLOR, help='Color for main text in ASS format (&HAABBGGRR)')
    parser.add_argument('--ruby-color', default=DEFAULT_RUBY_COLOR, help='Color for ruby text in ASS format (&HAABBGGRR)')
    parser.add_argument('--outline-color', default=DEFAULT_OUTLINE_COLOR, help='Color for text outline in ASS format (&HAABBGGRR)')
    parser.add_argument('--shadow-color', default=DEFAULT_SHADOW_COLOR, help='Color for text shadow in ASS format (&HAABBGGRR)')
    parser.add_argument('--outline-size', type=int, default=DEFAULT_OUTLINE_SIZE, help='Size of text outline')
    parser.add_argument('--shadow-size', type=int, default=DEFAULT_SHADOW_SIZE, help='Size of text shadow')
    
    return parser.parse_args()

if __name__ == "__main__":
    args = parse_args()
    
    # Create configuration from arguments
    config = {
        'font': args.font,
        'font_size': args.font_size,
        'ruby_font_size': args.ruby_font_size,
        'text_color': args.text_color,
        'ruby_color': args.ruby_color,
        'outline_color': args.outline_color,
        'shadow_color': args.shadow_color,
        'outline_size': args.outline_size,
        'ruby_outline_size': DEFAULT_RUBY_OUTLINE_SIZE,
        'shadow_size': args.shadow_size,
        'ruby_shadow_size': DEFAULT_RUBY_SHADOW_SIZE
    }
    
    process_directory(args.input_dir, args.output_dir, config) 